### ISSUE TITLE
Print help without dependencies

### ISSUE THREAD

**Issue by Dendraspis** [jlw4049/DeeZy#27]
When you want to get help while `dee.exe` and/or `ffmpeg.exe` are not available, the help won't be printed:
```
.\deezy.exe -h
dee.exe path not found
```

Would be nice to get the (basic) help regardless the dependencies, because they are not required yet.

**Comment by jlw4049** [comment]
I think this is a good idea. I'll get this implemented.

**Comment by jlw4049** [comment]
This is done in latest version
