### ISSUE TITLE
Exceeds path length for DEE

### ISSUE THREAD

**Issue by Lucane** [jlw4049/DeeZy#34]
> Path provided with input file exceeds path length for DEE.

DeeZy throws this error whenever I try to specify a temp directory with the "-tmp" switch.
If I use the default OS temp directory the command runs without issues.

<br>

> If `temp_dir` is provided, creates a directory with that name instead of a randomly generated one.
   If the length of the path to the input file plus the length of `temp_dir` exceeds 259 characters, raises a `PathTooLongError`.

The combined path length of my input file and temp directory does not exceed 259 characters. Here's the exact command I'm using:
`deezy encode ddp -t 0 -b 1536 -k -tmp "H:\temp_deezy" -o "H:\deezy.eac3" "H:\input.mkv"`

**Comment by jlw4049** [comment]
Thanks for the bug report, it's resolved in the latest version.

**Comment by Lucane** [comment]
Cheers for the quick fix! I didn't even notice the wrong inequality symbol 😄

**Comment by jlw4049** [comment]
> Cheers for the quick fix! I didn't even notice the wrong inequality symbol 😄

No problem. Can't believe I missed that myself :)
